// Action Types
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE'

export const FETCH_CITY_DETAILS_REQUESTED = 'FETCH_CITY_DETAILS_REQUESTED'
export const FETCH_CITY_DETAILS_FAILED = 'FETCH_CITY_DETAILS_FAILED'
export const FETCH_CITY_DETAILS_SUCCESS = 'FETCH_CITY_DETAILS_SUCCESS'

export const FETCH_LATEST_POLLUTION_MEASURMENTS_REQUESTED =
  'FETCH_LATEST_POLLUTION_MEASURMENTS_REQUESTED'
export const FETCH_LATEST_POLLUTION_MEASURMENTS_SUCCESS =
  'FETCH_LATEST_POLLUTION_MEASURMENTS_SUCCESS'
export const FETCH_LATEST_POLLUTION_MEASURMENTS_FAILED = 'FETCH_LATEST_POLLUTION_MEASURMENTS_FAILED'

export const FETCH_WIKIPEDIA_PAGE_IDS_REQUESTED = 'FETCH_WIKIPEDIA_PAGE_IDS_REQUESTED'
export const FETCH_WIKIPEDIA_PAGE_IDS_SUCCESS = 'FETCH_WIKIPEDIA_PAGE_IDS_SUCCESS'
export const FETCH_WIKIPEDIA_PAGE_IDS_FAILED = 'FETCH_WIKIPEDIA_PAGE_IDS_FAILED'

export const LOAD_SEARCH_VALUE_FROM_LOCAL_STORAGE = 'LOAD_SEARCH_VALUE_FROM_LOCAL_STORAGE'
export const SAVE_SEARCH_VALUE_TO_LOCAL_STORAGE = 'SAVE_SEARCH_VALUE_TO_LOCAL_STORAGE'

export const SAVE_CITY_DETAILS_TO_LOCAL_STORAGE = 'SAVE_CITY_DETAILS_TO_LOCAL_STORAGE'
export const LOAD_CITY_DETAILS_FROM_LOCAL_STORAGE = 'LOAD_CITY_DETAILS_FROM_LOCAL_STORAGE'
