// Action Types
export const FETCH_CITY_DETAILS_REQUESTED = 'FETCH_CITY_DETAILS_REQUESTED'
export const FETCH_CITY_DETAILS_FAILED = 'FETCH_CITY_DETAILS_FAILED'
export const FETCH_CITY_DETAILS_SUCCESS = 'FETCH_CITY_DETAILS_SUCCESS'

export const FETCH_LATEST_POLLUTION_MEASURMENTS_REQUESTED =
  'FETCH_LATEST_POLLUTION_MEASURMENTS_REQUESTED'
export const FETCH_LATEST_POLLUTION_MEASURMENTS_SUCCESS =
  'FETCH_LATEST_POLLUTION_MEASURMENTS_SUCCESS'
export const FETCH_LATEST_POLLUTION_MEASURMENTS_FAILED = 'FETCH_LATEST_POLLUTION_MEASURMENTS_FAILED'

export const FETCH_WIKIPEDIA_PAGE_IDS_REQUESTED = 'FETCH_WIKIPEDIA_PAGE_IDS_REQUESTED'
export const FETCH_WIKIPEDIA_PAGE_IDS_SUCCESS = 'FETCH_WIKIPEDIA_PAGE_IDS_SUCCESS'
export const FETCH_WIKIPEDIA_PAGE_IDS_FAILED = 'FETCH_WIKIPEDIA_PAGE_IDS_FAILED'
